### ISSUE TITLE
Integrate automatic ApplicationVersion in publish worklfows for EMS

### ISSUE THREAD

**Issue by achobanov** [eSolutions-EMS/endurance-management-system#194]
## Using CI Build Number (e.g., GitHub run_number)
🔧 What is run_number?
In GitHub Actions, each workflow run has a unique, incremental number. Perfect for ApplicationVersion.

🛠️ Inject into MAUI Build
Update .csproj with placeholders:

```xml
<ApplicationDisplayVersion>1.4.2</ApplicationDisplayVersion>
<ApplicationVersion>$(BUILD_NUMBER)</ApplicationVersion>
```
In your GitHub Actions workflow:

```yaml
- name: Set version variables
  run: |
    echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

- name: Build MAUI iOS
  run: |
    dotnet build MyApp.csproj -c Release \
      -p:ApplicationVersion=${{ github.run_number }}
```

✅ Simple and works great for internal or test builds
⚠️ Requires you to manually manage ApplicationDisplayVersion

## Contract value
100 BGN
