### ISSUE TITLE
Improve solution setup for CICD

### ISSUE THREAD

**Issue by achobanov** [eSolutions-EMS/endurance-management-system#361]
## Overview
Using `Nuger.config` and `Directory.Build.props` helps setup common project properties and enforce analyzers in every project, but they cause challenges for CICD workflows. Investigate improvements

## Problems
The following has to be slapped at the start of every build job
```yaml
# Slap on top of every build: see 
    - name: Set current workding directory env
      run: echo "CURRENT_DIR=$(pwd)/src" >> $GITHUB_ENV
    # Necessary bacause dotnet restore fails otherwise
    - name: Remove local-cache NuGet source
      run: dotnet nuget remove source "local-cache" --configfile ./src/NuGet.config
```
and `SolutionDir` has to be passed with path to the src directory as MSBuild parameter like this:
```yaml
run: dotnet build -property:SolutionDir="$CURRENT_DIR" --no-restore ...
dotnet publish -property:SolutionDir="$CURRENT_DIR" --no-build "
```
